[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["DerekStride <djgstride@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
sha-1 = "0.8.2"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
http = "0.2"
percent-encoding = "2.1"
